version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: kavita-kavita_server_1
      APP_PORT: 5000

  server:
    image: kizaing/kavita:latest
    container_name: kavita
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - kavita-config:/kavita/config
      - kavita-books:/books

volumes:
  kavita-config:
  kavita-books:
